"""Tests for the credential-store crypto and read/write helpers."""

from __future__ import annotations

import json
import textwrap
import time
from pathlib import Path

import pytest

from pairflow import credentials, writer

# ---------------------------------------------------------------------------
# Crypto: encrypt / decrypt round-trips
# ---------------------------------------------------------------------------


def test_encrypt_decrypt_round_trip_with_secret():
    """Encrypting then decrypting returns the original store."""
    secret = "my-test-secret"
    store = {"nodeabc": {"username": "admin", "password": "hunter2"}}

    encrypted = credentials.encrypt_store(store, secret)
    assert "$" in encrypted

    decrypted = credentials.decrypt_store(encrypted, secret)
    assert decrypted == store


def test_encrypt_decrypt_round_trip_plaintext():
    """With secret=None, encrypt_store returns the store unchanged."""
    store = {"nodeabc": {"token": "open-secret"}}
    encrypted = credentials.encrypt_store(store, secret=None)
    assert encrypted == store  # no $ wrapper

    decrypted = credentials.decrypt_store(encrypted, secret=None)
    assert decrypted == store


def test_encrypt_produces_correct_format():
    """Encrypted value must be: 32 hex IV chars + valid base64 ciphertext."""
    import base64 as _b64

    secret = "format-check"
    encrypted = credentials.encrypt_store({"n": {"k": "v"}}, secret)
    encoded = encrypted["$"]

    # IV: 32 hex chars = 16 bytes
    iv_hex = encoded[:32]
    assert len(iv_hex) == 32
    assert bytes.fromhex(iv_hex)  # must be valid hex

    # Ciphertext: valid base64
    b64_part = encoded[32:]
    decoded = _b64.b64decode(b64_part)
    assert len(decoded) > 0


def test_decrypt_store_passthrough_when_no_dollar_key():
    """A plaintext store (no $ key) is returned as-is even when secret is set."""
    store = {"node1": {"token": "plaintext-value"}}
    # This can happen with a freshly initialised NR that hasn't written its
    # first encrypted cred file yet.
    result = credentials.decrypt_store(store, secret="some-secret")
    assert result == store


def test_encrypt_store_empty_dict():
    """Encrypting an empty store must round-trip back to an empty store."""
    secret = "empty-secret"
    enc = credentials.encrypt_store({}, secret)
    dec = credentials.decrypt_store(enc, secret)
    assert dec == {}


# ---------------------------------------------------------------------------
# Regression fixture: guard against algorithm changes
#
# The fixture below was generated by running this Python snippet once:
#
#   import hashlib, base64, json
#   from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
#
#   secret = "reg-test-secret"
#   store   = {"node1": {"pw": "abc"}}
#   key     = hashlib.sha256(secret.encode()).digest()
#   iv      = bytes.fromhex("deadbeefcafebabe0011223344556677")
#   pt      = json.dumps(store).encode()
#   c       = Cipher(algorithms.AES(key), modes.CTR(iv))
#   enc     = c.encryptor()
#   ct      = enc.update(pt) + enc.finalize()
#   print("deadbeefcafebabe0011223344556677" + base64.b64encode(ct).decode())
#   # → "deadbeefcafebabe0011223344556677b7DqpeHBlBLo/m151jQero7d649ZeFKa"
#
# If this test fails the crypto algorithm was accidentally changed.
# ---------------------------------------------------------------------------

REGRESSION_SECRET = "reg-test-secret"
REGRESSION_STORE = {"node1": {"pw": "abc"}}
REGRESSION_ENCODED = "deadbeefcafebabe0011223344556677b7DqpeHBlBLo/m151jQero7d649ZeFKa"


def test_decrypt_known_fixture():
    """Decrypting the hardcoded fixture returns the known store."""
    raw = {"$": REGRESSION_ENCODED}
    result = credentials.decrypt_store(raw, REGRESSION_SECRET)
    assert result == REGRESSION_STORE


def test_encrypt_with_known_iv_matches_fixture(monkeypatch):
    """Encrypting with a deterministic IV reproduces the fixture string."""
    fixed_iv = bytes.fromhex("deadbeefcafebabe0011223344556677")
    monkeypatch.setattr("os.urandom", lambda n: fixed_iv[:n])

    enc = credentials.encrypt_store(REGRESSION_STORE, REGRESSION_SECRET)
    assert enc["$"] == REGRESSION_ENCODED


# ---------------------------------------------------------------------------
# resolve_secret
# ---------------------------------------------------------------------------


def test_resolve_secret_from_settings_js_double_quotes(tmp_path: Path):
    settings = tmp_path / "settings.js"
    settings.write_text(textwrap.dedent("""
        module.exports = {
            credentialSecret: "my-double-quoted-secret",
        };
    """))
    assert credentials.resolve_secret(tmp_path) == "my-double-quoted-secret"


def test_resolve_secret_from_settings_js_single_quotes(tmp_path: Path):
    settings = tmp_path / "settings.js"
    settings.write_text("    credentialSecret: 'single-quoted',\n")
    assert credentials.resolve_secret(tmp_path) == "single-quoted"


def test_resolve_secret_false_returns_none(tmp_path: Path):
    settings = tmp_path / "settings.js"
    settings.write_text("credentialSecret: false,\n")
    assert credentials.resolve_secret(tmp_path) is None


def test_resolve_secret_falls_back_to_config_runtime_json(tmp_path: Path):
    """No settings.js → read _credentialSecret from .config.runtime.json."""
    cfg = tmp_path / ".config.runtime.json"
    cfg.write_text(json.dumps({"_credentialSecret": "runtime-secret"}))
    assert credentials.resolve_secret(tmp_path) == "runtime-secret"


def test_resolve_secret_falls_back_to_config_json(tmp_path: Path):
    """No settings.js or .config.runtime.json → read .config.json."""
    cfg = tmp_path / ".config.json"
    cfg.write_text(json.dumps({"_credentialSecret": "legacy-secret"}))
    assert credentials.resolve_secret(tmp_path) == "legacy-secret"


def test_resolve_secret_prefers_settings_js_over_config(tmp_path: Path):
    """settings.js takes precedence over .config.runtime.json."""
    settings = tmp_path / "settings.js"
    settings.write_text("credentialSecret: 'from-settings',\n")
    cfg = tmp_path / ".config.runtime.json"
    cfg.write_text(json.dumps({"_credentialSecret": "from-config"}))
    assert credentials.resolve_secret(tmp_path) == "from-settings"


def test_resolve_secret_raises_when_nothing_found(tmp_path: Path):
    """When no source provides a secret, a helpful ValueError is raised."""
    with pytest.raises(ValueError, match="Cannot determine the Node-RED credential secret"):
        credentials.resolve_secret(tmp_path)


def test_resolve_secret_settings_js_without_credential_secret_falls_through(tmp_path: Path):
    """A settings.js without credentialSecret key falls through to config files."""
    settings = tmp_path / "settings.js"
    settings.write_text("module.exports = { adminAuth: {} };\n")
    cfg = tmp_path / ".config.json"
    cfg.write_text(json.dumps({"_credentialSecret": "fallback"}))
    assert credentials.resolve_secret(tmp_path) == "fallback"


# ---------------------------------------------------------------------------
# set_node_credentials / list / delete — encrypted path
# ---------------------------------------------------------------------------


@pytest.fixture
def cred_setup(tmp_path: Path):
    """Return (cred_file, secret, initial_store)."""
    secret = "test-cred-secret"
    store = {"existing": {"token": "old-token"}}
    cred_file = tmp_path / "flows_cred.json"
    cred_file.write_text(
        json.dumps(credentials.encrypt_store(store, secret)),
    )
    return cred_file, secret, store


def test_set_credentials_creates_new_entry(cred_setup):
    cred_file, secret, _ = cred_setup
    result = credentials.set_node_credentials(
        cred_file, "newnode", {"api_key": "xyz"}, secret,
    )
    assert result["node_id"] == "newnode"
    assert result["keys_set"] == ["api_key"]
    assert result["merged"] is False  # no prior entry

    store = credentials.read_store(cred_file, secret)
    assert "api_key" in store["newnode"]
    # Value is present in the store (unencrypted form after decrypt).
    assert store["newnode"]["api_key"] == "xyz"


def test_set_credentials_merge_adds_to_existing(cred_setup):
    cred_file, secret, _ = cred_setup
    # First write one field.
    credentials.set_node_credentials(
        cred_file, "multifield", {"username": "u"}, secret,
    )
    # Now merge a second field.
    result = credentials.set_node_credentials(
        cred_file, "multifield", {"password": "p"}, secret, merge=True,
    )
    assert result["merged"] is True
    assert result["keys_set"] == ["password"]

    store = credentials.read_store(cred_file, secret)
    assert store["multifield"]["username"] == "u"
    assert store["multifield"]["password"] == "p"


def test_set_credentials_replace_overwrites_all(cred_setup):
    cred_file, secret, _ = cred_setup
    credentials.set_node_credentials(
        cred_file, "multifield", {"username": "u", "password": "p"}, secret,
    )
    credentials.set_node_credentials(
        cred_file, "multifield", {"token": "t"}, secret, merge=False,
    )
    store = credentials.read_store(cred_file, secret)
    assert "token" in store["multifield"]
    assert "username" not in store["multifield"]


def test_set_credentials_creates_file_when_absent(tmp_path: Path):
    """set_node_credentials creates the cred file if it does not yet exist."""
    cred_file = tmp_path / "new_cred.json"
    assert not cred_file.exists()
    secret = "new-file-secret"

    result = credentials.set_node_credentials(
        cred_file, "nodeX", {"key": "val"}, secret,
    )
    assert cred_file.exists()
    assert result["node_id"] == "nodeX"
    store = credentials.read_store(cred_file, secret)
    assert store["nodeX"]["key"] == "val"


def test_set_credentials_optimistic_lock(cred_setup):
    """Concurrent modification of the cred file raises ConcurrentModificationError."""
    cred_file, secret, store = cred_setup
    mtime = writer.current_mtime(cred_file)

    # Simulate external modification.
    time.sleep(0.05)
    cred_file.write_text(
        json.dumps(credentials.encrypt_store({"changed": {"by": "other"}}, secret)),
    )

    with pytest.raises(writer.ConcurrentModificationError):
        writer.atomic_write_json(
            cred_file,
            credentials.encrypt_store(store, secret),
            expected_mtime=mtime,
        )


# ---------------------------------------------------------------------------
# set_node_credentials / list / delete — plaintext (secret=None) path
# ---------------------------------------------------------------------------


@pytest.fixture
def plain_cred_file(tmp_path: Path) -> Path:
    store = {"node_plain": {"field": "value"}}
    p = tmp_path / "flows_cred.json"
    p.write_text(json.dumps(store))
    return p


def test_set_credentials_plaintext(plain_cred_file: Path):
    credentials.set_node_credentials(
        plain_cred_file, "node_new", {"k": "v"}, secret=None,
    )
    store = credentials.read_store(plain_cred_file, secret=None)
    assert store["node_new"]["k"] == "v"
    assert store["node_plain"]["field"] == "value"  # existing entry intact


def test_list_credentials_keys_only(cred_setup):
    """list_node_credentials returns key names, never values."""
    cred_file, secret, _ = cred_setup
    credentials.set_node_credentials(
        cred_file, "nodeA", {"username": "admin", "password": "pw"}, secret,
    )
    result = credentials.list_node_credentials(cred_file, secret)

    assert result["count"] >= 2
    by_id = {n["node_id"]: n["keys"] for n in result["nodes"]}

    assert sorted(by_id["nodeA"]) == ["password", "username"]
    # Values must not appear anywhere in the result.
    result_str = json.dumps(result)
    assert "admin" not in result_str
    assert "pw" not in result_str


def test_list_credentials_missing_file(tmp_path: Path):
    """list_node_credentials on a non-existent file returns empty."""
    result = credentials.list_node_credentials(tmp_path / "no.json", secret="s")
    assert result == {"count": 0, "nodes": []}


def test_delete_credentials_removes_entry(cred_setup):
    cred_file, secret, _ = cred_setup
    result = credentials.delete_node_credentials(cred_file, "existing", secret)
    assert result == {"deleted": "existing", "found": True}

    store = credentials.read_store(cred_file, secret)
    assert "existing" not in store


def test_delete_credentials_missing_raises(cred_setup):
    cred_file, secret, _ = cred_setup
    with pytest.raises(KeyError):
        credentials.delete_node_credentials(cred_file, "no-such-node", secret)


def test_delete_credentials_missing_ok(cred_setup):
    cred_file, secret, _ = cred_setup
    result = credentials.delete_node_credentials(
        cred_file, "no-such-node", secret, missing_ok=True,
    )
    assert result == {"deleted": None, "found": False}


def test_delete_credentials_missing_file_missing_ok(tmp_path: Path):
    result = credentials.delete_node_credentials(
        tmp_path / "no.json", "node1", "secret", missing_ok=True,
    )
    assert result == {"deleted": None, "found": False}


def test_delete_credentials_missing_file_raises(tmp_path: Path):
    with pytest.raises(KeyError, match="Credential file not found"):
        credentials.delete_node_credentials(
            tmp_path / "no.json", "node1", "secret", missing_ok=False,
        )
